const GEOREF_PROVEEDOR_NOMINATIM = 'nominatim';
const GEOREF_PROVEEDOR_HERE = 'here';

const GEOREF_PROVEEDORES = [GEOREF_PROVEEDOR_NOMINATIM, GEOREF_PROVEEDOR_HERE];

const GEOREF_PROVEEDOR_LABELS = {
  [GEOREF_PROVEEDOR_NOMINATIM]: 'OpenStreetMap (Nominatim) — gratuito',
  [GEOREF_PROVEEDOR_HERE]: 'HERE — recomendado LatAm',
};

module.exports = {
  GEOREF_PROVEEDOR_NOMINATIM,
  GEOREF_PROVEEDOR_HERE,
  GEOREF_PROVEEDORES,
  GEOREF_PROVEEDOR_LABELS,
};
