const { Router } = require('express');

const auth = require('./auth');
const catalogos = require('./catalogos');
const alumnos = require('./alumnos');
const matriculas = require('./matriculas');
const liquidacion = require('./liquidacion');
const ingresos = require('./ingresos');
const certificados = require('./certificados');
const config = require('./config');
const usuarios = require('./usuarios');
const programas = require('./programas');
const servicios = require('./servicios');
const egresos = require('./egresos');
const rrhh = require('./rrhh');
const caja = require('./caja');
const auditoria = require('./auditoria');
const actividad = require('./actividad');
const dashboard = require('./dashboard');
const roles = require('./roles');
const jornadas = require('./jornadas');
const vehiculos = require('./vehiculos');
const programacionCea = require('./programacionCea');
const cohortesAcademicas = require('./cohortesAcademicas');
const facturacion = require('./facturacion');
const aulaVirtual = require('./aulaVirtual');

const router = Router();

router.use('/auth', auth);
router.use('/catalogos', catalogos);
router.use('/alumnos', alumnos);
router.use('/matriculas', matriculas);
router.use('/liquidacion', liquidacion);
router.use('/ingresos', ingresos);
router.use('/certificados', certificados);
router.use('/config', config);
router.use('/usuarios', usuarios);
router.use('/programas', programas);
router.use('/servicios', servicios);
router.use('/rrhh', rrhh);
router.use('/egresos', egresos);
router.use('/caja', caja);
router.use('/auditoria', auditoria);
router.use('/actividad', actividad);
router.use('/dashboard', dashboard);
router.use('/roles', roles);
router.use('/jornadas', jornadas);
router.use('/sedes', require('./sedes'));
router.use('/vehiculos', vehiculos);
router.use('/programacion-cea', programacionCea);
router.use('/cohortes-academicas', cohortesAcademicas);
router.use('/instructor-portal', require('./instructorPortal'));
router.use('/facturacion', facturacion);
router.use('/aula-virtual', aulaVirtual);
router.use('/clientes', require('./clientes'));
router.use('/sistema', require('./sistema'));
router.use('/migracion', require('./migracion'));
router.use('/informes', require('./informes'));
router.use('/pasarela', require('./pasarela'));
router.use('/webhooks', require('./webhooks'));
router.use('/combos', require('./combos'));
router.use('/foro', require('./foro'));

module.exports = router;
